apiVersion: v1
kind: Secret
metadata:
  name: dcba-secrets
  namespace: tango-development
  labels:
    app: dcba-backend
    environment: development
    team: backend
type: Opaque
stringData:
  # App Config
  NODE_ENV: "DEV"
  HOSTNAME_DEV: "127.0.0.1"
  HOSTNAME_PROD: "0.0.0.0"
  HOSTNAME_DNS_INTRASOFT_DCBA_BACKEND_SERVICE: "k8s-cluster.tango.rid-intrasoft.eu"
  HOSTNAME_DNS_RIASTONE_DCBA_BACKEND_SERVICE: "dcba-tango.riastone.eu"
  SERVER_INTERNAL_BIND_PORT: "3000"
  SERVER_EXTERNAL_BIND_PORT: "3001"
  LOCALIZATION_ALGORITHM_APPLIED: "RIA-ED"
  LOCALIZATION_ALGORITHM_SCRIPT_PATH: "BACKEND/SCRIPTS/LOCALIZATION/RIASTONE/EUCLIDEAN_DISTANCE.py"
  JWT_SECRET_KEY: "G&5@dWvX9#jY^!kL6f3F+v4V2r2OaKp7zQ1e8bZ*H9uN!cR"
  BACKEND_CONTAINER: "dcba-backend"

  # Mongo
  MONGO_INITDB_ADMIN_USERNAME: "admin-username"
  MONGO_INITDB_ADMIN_PASSWORD: "admin-password"
  MONGO_INITDB_DATABASE: "dcba-mongo-db-v1"
  MONGO_CONTAINER: "dcba-mongo-db"
  MONGO_INITDB_INTERNAL_PORT: "27017"
  MONGO_INITDB_EXTERNAL_PORT: "27018"
  MONGO_REPLICA_SET_NAME: "rs0"
  MONGO_DISABLE_IPV6: "true"
  MONGO_DB_URI: "mongodb://admin-username:admin-password@dcba-mongo-db:27018/dcba-mongo-db-v1?authSource=admin"
  MONGO_DB_DEVICE_SCHEME_PATH: "MONGO_DB/MODELS/DEVICE.js"
  MONGO_DB_SESSION_REQUEST_SCHEME_PATH: "MONGO_DB/MODELS/SESSION_REQUEST.js"
  MONGO_DB_DEVICE_ALERT_SCHEME_PATH: "MONGO_DB/MODELS/ALERTS.js"

  # Influx
  INFLUX_INITDB_ADMIN_USERNAME: "admin-username"
  INFLUX_INITDB_ADMIN_PASSWORD: "admin-password"
  INFLUX_INITDB_DATABASE: "dcba-influx-db-v1"
  INFLUX_CONTAINER: "dcba-influx-db"
  INFLUX_INITDB_AUTH_TOKEN: "QzaDsrfh8LkP0dnTmxj4fB4KAtQVZb-68BHqTTqWv2jie5daMLpEqeugbn1hIfbTcduNEuR8HAoUtVFjC2M3bw=="
  INFLUX_INITDB_ORG: "DCBA"
  INFLUX_INITDB_BUCKET: "DCBA"
  INFLUXDB_INTERNAL_PORT: "8086"
  INFLUXDB_EXTERNAL_PORT: "8087"
  INFLUX_DB_URI: "http://dcba-influx-db:8087"

  # Tango Verifier
  HOSTNAME_VERIFIER_NADIA_PLATFORM_AUTH_RESPONSE: "https://ips-verifier.tango.nadiaplatform.com/api/v1/authentication_response?state="
  HOSTNAME_VERIFIER_NADIA_PLATFORM_STARTSIOP_URL: "https://ips-verifier.tango.nadiaplatform.com/api/v1/startsiop"
  HOSTNAME_VERIFIER_NADIA_VERIFIER_CALLBACK_URL: "https://ui-backend.tango.nadiaplatform.com/auth_callback"
  #REDIRECT_BACKEND_CALLBACK_URL: "https://dcba-tango.riastone.eu/authenticator/auth-callback"
  REDIRECT_BACKEND_CALLBACK_URL: "https://k8s-cluster.tango.rid-intrasoft.eu/development/dcba-backend/authenticator/auth-callback"

