# ---------------------------------------------------------------------------------------------------------------------- #
# ------------------------------- DCBA Backend Deployment ------------------------------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcba-backend
  namespace: smart-manufacturing
  labels:
    app: dcba-backend
    type: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      type: back-end
  template:
    metadata:
      labels:
        app: dcba-backend
        type: back-end
    spec:
      imagePullSecrets:
        - name: regcred-rias
      
      containers:
        - name: dcba-backend
          image: harbor.tango.rid-intrasoft.eu/dcba/dcba-backend:latest-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: dcba-secrets


---
# ------------------------------- DCBA Backend Service ------------------------------- #
apiVersion: v1
kind: Service
metadata:
  name: dcba-backend
  namespace: smart-manufacturing
  labels:
    app: dcba-backend
spec:
  selector:
    app: dcba-backend
  type: NodePort
  ports:
    - port: 3001       # Port exposed in the internal cluster (external pod port)
      targetPort: 3000 # The dcba-backend continer port (internal pod port)
---
# ---------------------------------------------------------------------------------------------------------------------- #



















# ---------------------------------------------------------------------------------------------------------------------- #
# ------------------------------- MongoDB Deployment ------------------------------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcba-mongo-db
  namespace: smart-manufacturing
  labels:
    app: dcba-mongo-db
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcba-mongo-db
  template:
    metadata:
      labels:
        app: dcba-mongo-db
    spec:
      imagePullSecrets:
        - name: regcred-rias
      containers:
        - name: dcba-mongo-db
          image: harbor.tango.rid-intrasoft.eu/dcba/dcba-mongo-db:latest-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin-username"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "admin-password"
            - name: MONGO_INITDB_DATABASE
              value: "dcba-mongo-db-v1"
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db/
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: dcba-mongo-pvc

---
# ------------------------------- MongoDB Service ------------------------------- #
apiVersion: v1
kind: Service
metadata:
  name: dcba-mongo-db
  namespace: smart-manufacturing
  labels:
    app: dcba-mongo-db
spec:
  selector:
    app: dcba-mongo-db
  ports:
    - port: 27018       # Port exposed in the internal cluster (external pod port)
      targetPort: 27017 # The mongo-db continer port (internal pod port)

---
# ---------------------------------------------------------------------------------------------------------------------- #



















# ---------------------------------------------------------------------------------------------------------------------- #
# ------------------------------- InfluxDB Deployment ------------------------------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcba-influx-db
  namespace: smart-manufacturing
  labels:
    app: dcba-influx-db
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcba-influx-db
  template:
    metadata:
      labels:
        app: dcba-influx-db
    spec:
      imagePullSecrets:
        - name: regcred-rias
      containers:
        - name: dcba-influx-db
          image: harbor.tango.rid-intrasoft.eu/dcba/dcba-influx-db:latest-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: "admin-username"
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: "admin-password"
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: "DCBA"
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: "DCBA"
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: "QzaDsrfh8LkP0dnTmxj4fB4KAtQVZb-68BHqTTqWv2jie5daMLpEqeugbn1hIfbTcduNEuR8HAoUtVFjC2M3bw=="
          volumeMounts:
            - name: influxdb-storage
              mountPath: /var/lib/influxdb2
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: dcba-influx-pvc

---
# ------------------------------- InfluxDB Service ------------------------------- #
apiVersion: v1
kind: Service
metadata:
  name: dcba-influx-db
  namespace: smart-manufacturing
  labels:
    app: dcba-influx-db
spec:
  selector:
    app: dcba-influx-db
  ports:
    - port: 8087       # Port exposed in the internal cluster (external pod port)
      targetPort: 8086 # The InfluxDB continer port (internal pod port)
# ---------------------------------------------------------------------------------------------------------------------- #