# dcba-mongo-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcba-mongo-pvc
  namespace: tango-development
spec:
  accessModes:
    - ReadWriteMany # or ReadWriteMany (for 2+ replicas)
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi    # For only one replicas: local-path
                               # For multiple replicas (+2): nfs-csi

