---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcba-server
  namespace: tango-development
  labels:
    app: dcba-server
    type: back-end
spec:
  replicas: 2  # Defines how many identical pods to run.
  selector:
    matchLabels:
      type: back-end
  template:
    metadata:
      labels:
        app: dcba-server
        type: back-end
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: dcba-server
        image: harbor.tango.rid-intrasoft.eu/dcba/dcba_server_image:latest_dev
        imagePullPolicy: Always
        ports:
        - containerPort: ${SERVER_INTERNAL_BIND_PORT}   # Port the container will expose
        env:
        - name: MONGO_DB_URI
          value: "mongodb://dcba_mongo_db:${MONGO_INITDB_EXTERNAL_PORT}"  # MongoDB service URI
        - name: INFLUX_DB_URI
          value: "http://dcba_influx_db:${INFLUXDB_EXTERNAL_PORT}"  # InfluxDB service URI
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: root-password
        - name: INFLUX_INITDB_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: influx-secrets
              key: admin-username
        - name: INFLUX_INITDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influx-secrets
              key: admin-password
---
apiVersion: v1
kind: Service
metadata:
  name: dcba-server
  namespace: tango-development
  labels:
    app: dcba-server
spec:
  selector:
    app: dcba-server
  type: NodePort  # Service accessible via NodePort
  ports:
  - port: ${SERVER_EXTERNAL_BIND_PORT}        # The port that the Service will expose externally
    targetPort: ${SERVER_INTERNAL_BIND_PORT}  # The port on the container to forward traffic to
