# dcba-mongo-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcba-mongo-pvc
  namespace: tango-development
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path # For only one replicas: local-path
                               # For multiple replicas (+2): nfs-csi
