apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcba-influx-pvc
  namespace: tango-development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path  # Use nfs-csi if you need multiple replicas
