openapi: 3.0.0
info:
  title: DCBA Mechanisms API
  version: 1.0.0
  description: API documentation for the DCBA backend services

servers:
  - url: https://your-real-api-url.com/api
    description: Production server
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /employees/behavioural-score:
    post:
      summary: Get behavioural score
      description: Returns the employee's behavioural score based on DIDs and JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                didSP:
                  type: string
                didRequester:
                  type: string
                jwtAuth:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  behaviouralScore:
                    type: number
        '401':
          description: Unauthorized
        '404':
          description: Employee not found
