openapi: 3.0.0
info:
  title: DCBA Mechanisms API
  version: 1.0.0
  description: API documentation for the DCBA Services

servers:
  - url: https://tango-eu-project.github.io/DCBA-Mechanisms/

paths:
  /devices:
    get:
      summary: Fetch all devices
      description: Retrieves all device entries from the database.
      responses:
        '200':
          description: Successfully fetched devices
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Devices fetched successfully.
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        device_id:
                          type: string
                          example: "a4e4cf21ab7e"
                        did:
                          type: string
                          example: "did:example:123456789abcdefghi"
                        sub:
                          type: string
                          example: "user@example.com"
        '500':
          description: Server error while fetching devices
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Error fetching device data.

  /devices/online-shifts:
    get:
      summary: Fetch online devices
      description: Retrieves devices that are currently online.
      responses:
        '200':
          description: Successfully fetched online devices
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  statusCode:
                    type: integer
                    example: 200
                  statusMessage:
                    type: string
                    example: Fetched online devices successfully.
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        device_id:
                          type: string
                          example: "a4e4cf21ab7e"
                        did:
                          type: string
                          example: "did:example:123456789abcdefghi"
                        sub:
                          type: string
                          example: "user@example.com"
        '500':
          description: Server error while fetching online devices
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  statusCode:
                    type: integer
                    example: 500
                  statusMessage:
                    type: string
                    example: Error fetching online devices.

  /devices/offline-shifts:
    get:
      summary: Fetch offline devices
      description: Retrieves devices that are currently offline.
      responses:
        '200':
          description: Successfully fetched offline devices
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  statusCode:
                    type: integer
                    example: 200
                  statusMessage:
                    type: string
                    example: Fetched offline devices successfully.
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        device_id:
                          type: string
                          example: "a4e4cf21ab7e"
                        did:
                          type: string
                          example: "did:example:123456789abcdefghi"
                        sub:
                          type: string
                          example: "user@example.com"
        '500':
          description: Server error while fetching offline devices
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  statusCode:
                    type: integer
                    example: 500
                  statusMessage:
                    type: string
                    example: Error fetching offline devices.

  /devices/behavioural-score:
    post:
      summary: Fetch behavioural score of a device
      description: Returns the device's behavioural score based on the provided DIDs and JWT authorization.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                didSP:
                  type: string
                  example: "did:example:service-provider"
                didRequester:
                  type: string
                  example: "did:example:123456789abcdefghi"
                jwtAuth:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        '200':
          description: Successfully fetched behavioural score
          content:
            application/json:
              schema:
                type: object
                properties:
                  behaviouralScore:
                    type: number
                    example: 0.65
        '400':
          description: Missing required fields or invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Missing required fields: didSP, didRequester, or jwtAuth."
        '401':
          description: Unauthorized - Invalid or expired JWT
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Invalid or expired JWT token."
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Device not found."

  /devices/last-location:
    post:
      summary: Fetch last known geographic coordinates of a device
      description: Returns the device's last known location using the provided DIDs and JWT authorization.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                didSP:
                  type: string
                  example: "did:example:service-provider"
                didRequester:
                  type: string
                  example: "did:example:device-abc123"
                jwtAuth:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        '200':
          description: Successfully fetched last known coordinates
          content:
            application/json:
              schema:
                type: object
                properties:
                  lastCoordinates:
                    type: object
                    properties:
                      latitude:
                        type: number
                        example: 37.7749
                      longitude:
                        type: number
                        example: -122.4194
        '400':
          description: Missing required fields or invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Missing required fields: didSP, didRequester, or jwtAuth."
        '401':
          description: Unauthorized - Invalid or expired JWT
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Invalid or expired JWT token."
        '404':
          description: Device not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Device not found."

  /post-logs:
    post:
      summary: Capture Android device logs and perform optional localization.
      tags:
        - Autenticator Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - did
                - log
                - accessToken
              properties:
                did:
                  type: string
                  example: "device-123"
                  description: Decentralized identifier of the device.
                log:
                  type: string
                  example: "12-01 12:00:00.000 I/WifiNetworkScannerN: Found network"
                  description: The raw log data captured from the device.
                accessToken:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  description: The JWT session token verifying the request source.
      responses:
        '200':
          description: Returns status for all cases, success or error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  statusCode:
                    type: integer
                    example: 200
                  statusMessage:
                    type: string
                    example: Logs processed successfully.
              examples:
                Success:
                  value:
                    success: true
                    statusCode: 200
                    statusMessage: Logs processed successfully.
                MalformedLog:
                  value:
                    success: false
                    statusCode: 400
                    statusMessage: Malformed log detected
                MissingLogData:
                  value:
                    success: false
                    statusCode: 400
                    statusMessage: Log data cannot be empty.
                MissingTimestamp:
                  value:
                    success: false
                    statusCode: 400
                    statusMessage: Invalid log data. Missing timestamp.
                MissingAccessToken:
                  value:
                    success: false
                    statusCode: 400
                    statusMessage: Session token is required.
                InvalidTokenFormat:
                  value:
                    success: false
                    statusCode: 401
                    statusMessage: Invalid session token format.
                TokenDecodeFailed:
                  value:
                    success: false
                    statusCode: 401
                    statusMessage: Invalid session token.
                TokenExpired:
                  value:
                    success: false
                    statusCode: 401
                    statusMessage: Session token has expired.
                TokenMismatch:
                  value:
                    success: false
                    statusCode: 401
                    statusMessage: Token did does not match the provided did.
                LocalizationError:
                  value:
                    success: false
                    statusCode: 500
                    statusMessage: Failed to perform localization.
                InfluxStorageError:
                  value:
                    success: false
                    statusCode: 500
                    statusMessage: Failed to store logs in the Influx Database.
                ProcessingError:
                  value:
                    success: false
                    statusCode: 500
                    statusMessage: Internal Server Error


/devices/access-token-validation:
  post:
    summary: Validate the provided JWT token to ensure it is active and valid.
    tags:
      - Authenticator Endpoints
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - accessToken
            properties:
              accessToken:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                description: The JWT session token to be validated.
    responses:
      '200':
        description: Token validation result.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                statusCode:
                  type: integer
                  example: 200
                statusMessage:
                  type: string
                  example: Valid
                did:
                  type: string
                  example: "device-123"
                  description: Decentralized Identifier of the device (if valid).
                sub:
                  type: string
                  example: "auth-subject"
                  description: Subject claim from the token.
                verifiableCredential:
                  type: object
                  description: Verifiable credential object from the token.
            examples:
              Success:
                value:
                  success: true
                  statusCode: 200
                  statusMessage: Valid
                  did: "device-123"
                  sub: "auth-subject"
                  verifiableCredential:
                    id: "device-123"
                    issuer: "issuer.example"
              MissingToken:
                value:
                  success: false
                  statusCode: 200
                  statusMessage: No access token provided. Please log in again.
              InvalidFormat:
                value:
                  success: false
                  statusCode: 200
                  statusMessage: Invalid token format. Please log in again.
              ExpiredToken:
                value:
                  success: false
                  statusCode: 200
                  statusMessage: Token expired. Please log in again.
              InternalError:
                value:
                  success: false
                  statusCode: 200
                  statusMessage: Internal server error. Please try again later.

  